### ISSUE TITLE
Trouble installing AWAS

### ISSUE THREAD

**Issue by protoben** [sireum/osate-plugin-update-site#1]
Hi,

I'm trying to follow the AWAS installation steps [here](https://awas.sireum.org/doc/01-getting-started/index.html#sireum-awas-pluging-for-osate). When I try to add this plugin update site in OSATE, however, AWAS does not show up in the list of plugins.

I assume the documentation I'm using is old. Is there more current AWAS documentation available? Or is there some way for me to access the AWAS version referenced by this documentation?

Thanks,
-Ben Hamlin

**Comment by thari** [comment]
Uncheck "Group items by category" checkbox, you should be able to see Awas.

**Comment by protoben** [comment]
That worked. Thanks!
